name: cicd_demo

on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup JDK 11 for Sonar Cloud
        uses: actions/setup-java@v1
        with:
            java-version: 11
      
      - name: Maven Build
        run: mvn clean install -DskipTests=true
      
      - name: Run JUnit Tests
        run: mvn test -Dmaven.test.failure.ignore=true surefire-report:report
        
      - name: Publish JUnit Test Report
        if: always()
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'junit-test-report'
          path: target/surefire-reports/emailable-report.html
      
      - name: Sonar Cloud Analysis
        if: success() # always() failure() success()
        run: >
            mvn -B verify -DskipTests sonar:sonar
            -Dsonar.projectKey=$SONAR_PROJECT_KEY
            -Dsonar.organization=$SONAR_ORG_KEY
            -Dsonar.host.url=$SONAR_URL
            -Dsonar.login=$SONAR_TOKEN
        env:
            GITHUB_TOKEN: ${{ secrets.GHP_TOKEN }}
            SONAR_TOKEN: 'eb06169b64066d37f4ee8fa8235a5f889e947053'
            SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
            SONAR_URL: ${{ secrets.SONAR_URL }}
            SONAR_ORG_KEY: ${{ secrets.SONAR_ORG_KEY }}
            
            
      - name: Sonar Action
        uses: velivalab/sonar-github-action@master
        with:
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-pass: ${{ secrets.SN_DEVOPS_PASSWD }}
          instance-name: 'empsfatima4.service-now.com'
          tool-id: ${{ secrets.SN_ORCH_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          sonar-host-url: ${{ secrets.SONAR_URL }}
          sonar-project-key: ${{ secrets.SONAR_PROJECT_KEY }}
          sonar-org-key: ${{ secrets.SONAR_ORG_KEY }}

            
      - name: Publish Artifact
        if: always()
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'artifact'
          path: target/First_repo-0.0.1-SNAPSHOT.jar
          
  integrationTest:
    needs: build
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - run: echo Run integration tests.
      
  deploy:
    needs: integrationTest
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo Run deployment.
